### ISSUE TITLE
The lng value is being rendered infinitely from the server component to the client component.

### ISSUE THREAD

**Issue by HakanSungur** [i18next/next-i18next#2303]
I followed all the details in the article at https://locize.com/blog/next-app-dir-i18n/. I did the same thing. I am using React 18 and Next.js 14. In the server component, I am passing the value obtained from params: { lng } to my client component as props. When I use const { t } = useTranslation(lng) in the client component, my client component renders infinitely. However, when I do not pass the lng value with const { t } = useTranslation(), I get an error saying that the UI components are not the same on the server side and client side. Additionally, when I use /stays instead of {lng}/stays, I want it to automatically convert to en/stays. I managed to achieve this before, but it broke again. I have configured i18n in CRA applications for years, but I am struggling for the first time. I want these issues to be resolved. You can use your own repository from the source mentioned above.

**Comment by adrai** [comment]
Please fork this repository (https://github.com/i18next/next-app-dir-i18next-example) and adapt it until you can reproduce your issue.

fyi: you always need to pass the lng value for the useTranslation function, since there is no way on server side to get it magically from somewhere else...

**Comment by HakanSungur** [comment]
https://github.com/HakanSungur/next-app-dir-i18next-example I created an example for you here. When I write Console.log(lng), you can see that lng is constantly written to the console.

**Comment by adrai** [comment]
Sorry @HakanSungur but that's not really a minimal reproducible example...
That's full of other dependencies, components, hooks, etc...
Please remove all that, and only add the minimal relevant code that shows your issue based on this repository: https://github.com/i18next/next-app-dir-i18next-example

btw. I cannot even "npm install" it:
```
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: react-dates@21.8.0
npm error Found: react@18.3.1
npm error node_modules/react
npm error   react@"18.3.1" from the root project
npm error   peer react@">=16.8.0" from @floating-ui/react@0.26.27
npm error   node_modules/@floating-ui/react
npm error     @floating-ui/react@"^0.26.16" from @headlessui/react@2.2.0
npm error     node_modules/@headlessui/react
npm error       @headlessui/react@"^2.2.0" from the root project
npm error     @floating-ui/react@"^0.26.23" from react-datepicker@7.5.0
npm error     node_modules/react-datepicker
npm error       react-datepicker@"^7.5.0" from the root project
npm error   19 more (@floating-ui/react-dom, @headlessui/react, ...)
npm error
npm error Could not resolve dependency:
npm error peer react@"^0.14 || ^15.5.4 || ^16.1.1" from react-dates@21.8.0
npm error node_modules/react-dates
npm error   react-dates@"^21.8.0" from the root project
npm error
npm error Conflicting peer dependency: react@16.14.0
npm error node_modules/react
npm error   peer react@"^0.14 || ^15.5.4 || ^16.1.1" from react-dates@21.8.0
npm error   node_modules/react-dates
npm error     react-dates@"^21.8.0" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
```

beside that, I can see the HeroSearchForm component is a client side only component but, you use it in the SectionHero component, that is server side only... maybe that is causing that rerender issue...
you may want to try to split that into 3 parts (one for server side, one for client and one base (independent)), like done here with the Footer: https://github.com/i18next/next-app-dir-i18next-example/tree/main/app/%5Blng%5D/components/Footer

**Comment by HakanSungur** [comment]
Could you please try running npm i --force?

**Comment by adrai** [comment]
> Could you please try running npm i --force?

Already done that... but have you done the rest of what I told you?

**Comment by HakanSungur** [comment]
I couldn't understand this. You wanted me to divide the server component into 3. However, in the Next documentation, it says that I can use the server component inside the server component and the client component inside it. I will also minimize the code and give information again.

**Comment by adrai** [comment]
> I couldn't understand this. You wanted me to divide the server component into 3. However, in the Next documentation, it says that I can use the server component inside the server component and the client component inside it. I will also minimize the code and give information again.

If so, then please change the footer in my example accordingly and check if there is an issue with that: https://github.com/i18next/next-app-dir-i18next-example/blob/main/app/%5Blng%5D/components/Footer/index.js

In past having a server component that loaded a client component or vice-versa raised issues, that's why it's splitted in 3 parts. If that's not the case anymore, I'll investigate what Next.js changed... but I suspect that's still an issue and you have to split it.

**Comment by HakanSungur** [comment]
As you said, I will divide the server component into 3. But in this case, I will have to divide all the components that have a client under them and vice versa. Although I don't fully understand why we are doing this, I will do my best to solve the problem and divide the server component into 3. However, if I knew that I have 200 components like this, I would never switch to the next framework.

**Comment by HakanSungur** [comment]
Hello again,
I saved the application from most of the 3rd party applications. I pushed it again. I would be glad if you look at the console. I encounter a problem when I give lng as a prop to my StaySearchForm component. However, I do not encounter it when I do not give the lng value. https://github.com/HakanSungur/next-app-dir-i18next-example

**Comment by adrai** [comment]
You forgot to pass the lng to the useTranslation hook: 
<img width="331" alt="image" src="https://github.com/user-attachments/assets/2f2f5ad5-0f4c-4047-958a-f82540148fda">

**Comment by HakanSungur** [comment]
I've been developing with CRA for a long time, and I'm transitioning to Next.js for the first time, so I'm finding it challenging to understand. I believe the issue is resolved now. From what I understand, if the lng is forgotten within useTranslation(), it causes an infinite loop. Additionally, I’ll continue without dividing the components into three parts. Thank you for your help. The loop happened because I forgot the "lng" value in useTranslation(lng) in a client component. Thanks again for your assistance. You can close the topic.
